inventory/api/urls.py
from django.urls import path

from inventory.api.views import InventoryListAPIView

app_name = 'inventory-api'

urlpatterns = [
    path('', InventoryListAPIView.as_view(), name='inventory_list')
]

inventory/urls.py
from django.urls import path

from inventory.views import InventoryListView, InventoryDetailView

app_name = 'inventory'

urlpatterns = [
    path('', InventoryListView.as_view(), name='inventory_list'),
    path('<int:pk>/', InventoryDetailView.as_view(), name='inventory_detail')
]

inventory_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/inventory/')),

    # Views
    path('inventory/', include('inventory.urls')),

    # API Endpoints
    path('api/inventory/', include('inventory.api.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

accounts/models.py
from django.contrib.auth.models import AbstractUser as BaseUser, UserManager as BaseUserManager
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    pass


class User(BaseUser):
    objects = UserManager()

    class Meta:
        ordering = ['-id']
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        return self.username

    @property
    def full_name(self):
        return self.get_full_name()

core/models.py
from django.db import models


class AbstractTimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """ Ensures modified_at is updated when update_fields is passed """
        if update_fields and 'modified_at' not in update_fields:
            update_fields.append('modified_at')
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

inventory/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import AbstractTimestampModel


class Inventory(AbstractTimestampModel):
    name = models.CharField(verbose_name=_('Name'), max_length=200)
    description = models.CharField(verbose_name=_('Description'), max_length=255)
    notes = models.TextField(verbose_name=_('Notes'), blank=True)
    stock = models.PositiveIntegerField(verbose_name=_('Stock'), default=0)
    availability = models.BooleanField(verbose_name=_('Availability'), default=False)
    supplier = models.ForeignKey(
        verbose_name=_('Supplier'),
        to='Supplier',
        related_name='inventories',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ['-id']
        verbose_name = _('Inventory')
        verbose_name_plural = _('Inventories')

    def __str__(self):
        return self.name


class Supplier(AbstractTimestampModel):
    name = models.CharField(verbose_name=_('Name'), max_length=200)

    class Meta:
        ordering = ['-id']
        verbose_name = _('Supplier')
        verbose_name_plural = _('Suppliers')

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

core/views.py
from django.shortcuts import render

# Create your views here.

inventory/api/views.py
from rest_framework.generics import ListAPIView

from inventory.api.filters import InventoryFilter
from inventory.api.serializers import InventorySerializer
from inventory.models import Inventory


class InventoryListAPIView(ListAPIView):
    serializer_class = InventorySerializer
    filterset_class = InventoryFilter

    def get_queryset(self):
        return Inventory.objects.select_related('supplier')

inventory/views.py
from django.views.generic import ListView, DetailView

from inventory.models import Inventory


class InventoryListView(ListView):
    queryset = Inventory.objects.all()
    context_object_name = 'inventories'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'home_nav': 'active'
        })
        return context


class InventoryDetailView(DetailView):
    model = Inventory
    context_object_name = 'inventory'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'home_nav': 'active'
        })
        return context

inventory/templates/inventory/base.html
{% extends 'base.html' %}

inventory/templates/inventory/inventory_detail.html
{% extends 'inventory/base.html' %}
{% load static %}

{% block title %} Inventory Detail {% endblock title %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center my-4">
        <div class="card" style="width: 25rem;">
            <img src="{% static 'images/no-image.jpg' %}" class="card-img-top" alt="Image">

            <div class="card-body text-center">
                <h4 class="card-title"> {{ inventory.name }} </h4>
                <hr />

                <strong> Description </strong>
                <p class="card-text"> {{ inventory.description }} </p>

                {% if inventory.notes %}
                    <strong> Notes </strong>
                    <p class="card-text"> {{ inventory.notes }} </p>
                {% endif %}

                <p> <span class="text-danger"> Supplier: </span> {{ inventory.supplier.name }} </p>
                {% if inventory.stock %}
                    <p> <span class="text-info"> Stock: </span> {{ inventory.stock }} </p>
                {% endif %}

                <h6 class="{% if inventory.availability %} text-success {% else %} text-warning {% endif %}">
                    {% if inventory.availability %} In stock {% else %} Out of stock {% endif %}
                </h6>
            </div>
        </div>
    </div>
{% endblock %}

inventory/templates/inventory/inventory_list.html
{% extends 'inventory/base.html' %}

{% block title %} Inventory List {% endblock title %}

{% block content %}
    <div class="d-flex justify-content-center align-items-center">
        <div class="input-group mt-4" style="width: 400px;">
          <span class="input-group-text">Search</span>
          <input
                  type="text"
                  id="search-text"
                  class="form-control"
                  placeholder="Search Text"
                  aria-label="Search"
                  aria-labelledby="Search"
                  onchange="filterInventories()"
          >
        </div>
    </div>

    <div class="inventory-list row d-flex justify-content-center align-items-center my-4"></div>
{% endblock content %}

{% block extra_body %}
    <script>
        const fetchInventories = async (name) => {
            const url = `{% url 'inventory-api:inventory_list' %}` + (name !== undefined ? `?name=${name}` : '');
            const response = await fetch(url);
            if (response.status !== 200) {
                alert('Something went wrong!!');
            }
            return await response.json();
        };

        const renderInventory = inventory => {
            const availabilityColor = inventory.availability ? 'text-success' : 'text-warning';
            const availabilityText = inventory.availability ? 'In stock' : 'Out of stock';
            return `
                <div class="col-sm-12 col-lg-3 m-2" onclick="viewInventory(${inventory.id})">
                    <div class="card cursor-pointer highlight-hover">
                        <div class="card-body text-center">
                            <p> ${ inventory.name } </p>
                            <p> <span class="text-danger"> Supplier: </span> ${ inventory.supplier.name } </p>
                            <p class="${availabilityColor}">${availabilityText}</p>
                        </div>
                    </div>
                </div>
            `;
        }

        const renderNoContent = () => {
            return `
            <div class="no-content">
                <h2 class="text-danger"> No Content Found! </h2>
            </div>
            `;
        };

        const renderInventories = async () => {
            const queryParams = parseQueryParams();
            const inventoryHolder = document.querySelector('.inventory-list');
            const inventories = await fetchInventories(queryParams.name);
            inventoryHolder.innerHTML = inventories.map(renderInventory).join('') || renderNoContent();
        };

        const viewInventory = inventoryId => {
            window.location = `{% url 'inventory:inventory_detail' 123 %}`.replace('/123/', `/${inventoryId}/`);
        };

        const filterInventories = async () => {
            const inventoryHolder = document.querySelector('.inventory-list');
            const searchText = document.querySelector('#search-text').value;

            // Update Contents
            const inventories = await fetchInventories(searchText);
            inventoryHolder.innerHTML = inventories.map(renderInventory).join('') || renderNoContent();

            // Update URL
            const newUrl = window.location.pathname + (searchText ? `?name=${searchText}` : '');
            history.replaceState({}, undefined, newUrl);
        };

        document.addEventListener("DOMContentLoaded", function(event) {
            renderInventories();
        });
    </script>
{% endblock extra_body %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} Inventory {% endblock title %}
    </title>

    <link href="{% static 'core/base.css' %}" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% block extra_head %} {% endblock extra_head %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inventory:inventory_list' %}">Inventory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link {{ home_nav }}" href="{% url 'inventory:inventory_list' %}">
                                Home
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            {% block content %} {% endblock content %}
        </div>
    </main>

    <!-- Bootstrap Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <script>
        const parseQueryParams = () => {
            const paramPairs = window.location.search.slice(1).split('&');
            if (paramPairs[0] === '') return {};
            return paramPairs.reduce((data , pair) => {
                const [key, value] = pair.split('=');
                return {
                    ...data,
                    [key]: value
                };
            }, {});
        };
    </script>

    {% block extra_body %} {% endblock extra_body %}
</body>
</html>